[tool.poetry]
name = "py-multiauth"
version = "1.7.0"
description = "Python package to interact with multiple authentication services"
authors = ["Escape Technologies SAS <ping@escape.tech>"]
maintainers = [
    "Antoine Carossio <antoine@escape.tech>",
    "Karim Reda <karim.reda@escape.tech>",
    "Swan <swan@escape.tech>"
]
license = "MIT"
packages = [
    { include = "multiauth" }
]
include = [
    "LICENSE",
]
readme = "README.md"
"homepage" = "https://escape.tech/"
"repository" = "https://github.com/Escape-Technologies/py-multiauth"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/Escape-Technologies/py-multiauth/issues"

[tool.coverage.run]
omit = [
    'tests/*',
    'examples/*',
]

[tool.pytest.ini_options]
asyncio_mode = 'strict'

[tool.poetry.dependencies]
Authlib = "^1.0.1"
graphql-core = "^3.2.1"
pycognito = "^2022.5.0"
pydash = "^5.1.0"
PyJWT = "^2.4.0"
python = ">=3.7,<3.11"
jsonschema = "^4.7.2"

[tool.poetry.dev-dependencies]
autoflake = "^1.4"
docformatter = "^1.4"
isort = "^5.10.1"
mypy = "^0.971"
poetryup = "^0.10.0"
pylint = "^2.13.9"
pylint-quotes = "^0.2.3"
pytest = "^7.1.2"
pytest-asyncio = "^0.19.0"
pytest-cov = "^3.0.0"
pytest-mock = "^3.8.2"
setuptools = "^45"
types-boto3 = "^1.0.2"
types-requests = "^2.28.1"
unify = "^0.5"
vulture = "^2.5"
yapf = "^0.32.0"
Jinja2 = "^3.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
